### ISSUE TITLE
Specify number of usable threads in technical info

### ISSUE THREAD

**Issue by ErikBcd** [software-challenge/docs#102]
It's not fully clear whether 1 or 2 threads are usable by a client, since the [Technical Info](https://github.com/software-challenge/docs/blob/main/hyperbook/book/entwicklung/abgabe.md#technische-daten-f%C3%BCr-die-ausf%C3%BChrung-der-computerspieler) mentions that a player can use a full core (which would contain 2 threads as per Intel specification), while the [Garbage Collection FAQ entry](https://github.com/software-challenge/docs/blob/main/hyperbook/book/faq.md#garbage-collector) mentions that only one thread is usable

I can fix that if needed, but first I want to make sure which version is correct - 1 thread or 2 threads

**Comment by xeruf** [comment]
Fixed by https://github.com/software-challenge/docs/commit/36b54ebf4ccf25fbb81cac38df96ef947f4636ea, thanks for the report
