### ISSUE TITLE
Rename this repo to just "docs" and create redirect

### ISSUE THREAD

**Issue by SKoschnicke** [software-challenge/docs#28]
For the redirect, we can use a new repository named as the old one and create a redirect page there (because we need a GitHub pages redirect).

**Comment by xerus2000** [comment]
New plan: Create a CNAME record from docs.software-challenge.de and update all links to that, then simply rename the repo after the finale.

**Comment by xeruf** [comment]
https://docs.software-challenge.de/ is live!
