### ISSUE TITLE
Move client-specific hand-in documentation to client readme

### ISSUE THREAD

**Issue by xeruf** [software-challenge/docs#37]

**Comment by SKoschnicke** [comment]
But add note that the information is of the readme of the respective client source!

**Comment by FalconsSky** [comment]
Do I understand it right, that you wanna change [this README](https://github.com/software-challenge/backend/blob/main/player/configuration/README.md)?

**Comment by xeruf** [comment]
The Java instructions go there, yes: https://docs.software-challenge.de/entwicklung/abgabe
The ruby, C# etc instructions go to the respective player templates.
