### ISSUE TITLE
Attribution in header

### ISSUE THREAD

**Issue by xeruf** [software-challenge/docs#45]
@SKoschnicke ich habe letztens bei der Haupt-Dokumentation deinen Namen und Datum aus dem Header rausgenommen, jetzt bin ich mit nicht mehr so sicher. Ist das irgendwie relevant? Die Kontakt-Email steht ja auch darunter in der info-box (wobei wir die vielleicht auch zu `info@software-challenge.de` ändern sollten).

**Comment by SKoschnicke** [comment]
Nein, ist nicht wichtig. Die info Adresse als Kontaktmöglichkeit ist gut.

**Comment by xeruf** [comment]
Fixed in f61111d6a07b5787599ca95215c64aa14060b550
