### ISSUE TITLE
Hyperbook post-conversion tasks (#55)

### ISSUE THREAD

**Issue by xeruf** [software-challenge/docs#56]
Now that https://github.com/software-challenge/docs/pull/55 is merged:

Die "Einführung in XML" gehört zum Beispiel ins Glossar.
Und wir müssen noch schauen, wie wir die spielunabhängige XML-Dokumentation so gestalten, dass es in der Entwicklungs-Sektion keine spielspezifischen Links gibt.

"Client" ist immer noch nicht eliminiert, obwohl abgehakt :/
Genauso wie die Verlinkung typischer Begriffe ins Glossar, da kann man nen ganz einfachen find-replace laufen lassen:

    rpl "Wettkampfsystem\b" ':t[Wettkampfsystem]{#contest}' --exclude=glossar.md

ich nutze da ein eigenes kleines skript, aber das geht auch ohne
(https://git.jfischer.org:444/xeruf/dotfiles/src/branch/main/.local/bin/scripts/rpl)

 /spiele/penguins/xml muss noch richtig tabellarisiert werden

**Comment by xeruf** [comment]
Update https://github.com/software-challenge/docs/pull/59

- [ ] check the grammar for "fortgeschrittener spieler", sometimes the case does not fit (falscher Fall)
- [ ] there are still links to `/glossary`, including some invalid ones, these should be migrated to the hyperbook syntax
- [ ] when it comes to development instructions, "SimpleClient" should be replaced by "Spielervorlage" rather than "Zufallsspieler"

> The terms in the XML documentation were not tables, however they were a little off so I have now aligned them

Missed one:
![image](https://user-images.githubusercontent.com/13354331/185741630-186e65e1-0de0-41d4-92dd-feec8f94b66c.png)

I still think it would be good to turn them into tables, or simple lists with colon. I definitely dislike sub-lists with a single entry.

**Comment by FalconsSky** [comment]
The term "Spielervorlage" is not intended to use.
See [here](https://www.notion.so/softwarechallenge/Begriffe-und-Corporate-Image-798185991f22459bb65e9002d6dd54a9#cc28b202deb947498bc8cb70789832c1).

**Comment by xeruf** [comment]
Jetzt schon, dieser Guide ist doch von mir geschrieben ;)
