### ISSUE TITLE
Fix broken links in hyperbook

### ISSUE THREAD

**Issue by Rechenmaschine** [software-challenge/docs#62]
Under `https://docs.software-challenge.de/allgemein/spiel` 

1. Hyperlink "...Das Spiel der Software-Challenge Germany 2023 ist [Hey, Danke für den Fisch](https://docs.software-challenge.de/spiele/penguins/penguins_spielregeln)" -> Page not found
2. Next page button links to Blokus. Maybe not intended behaviour?
<img width="755" alt="Screenshot 2022-08-24 134345" src="https://user-images.githubusercontent.com/59762566/186410127-38a44401-a001-42e4-843c-c7d0d0c9fe87.png">

**Comment by FalconsSky** [comment]
The problem currently exists because the web server is not configured correctly for NextJs. We will take care of this in the next week.
The fact that the button to next page is visible is a bug on side of the software and will hopefully be fixed in the near future.
