### ISSUE TITLE
Unify hand-in documentation

### ISSUE THREAD

**Issue by xeruf** [software-challenge/docs#92]
When uploading a player in the contest system, there is a text under "Weitere Informationen" mostly identical with the one down here in the docs: https://docs.software-challenge.de/allgemein/wettkampf#weitere-ausfhrungsumgebung
I find it misplaced, I would rather consider a page like https://docs.software-challenge.de/glossary/player or https://docs.software-challenge.de/entwicklung/abgabe

Meanwhile the explanation of the structure in https://docs.software-challenge.de/allgemein/wettkampf could be merged with https://software-challenge.de/ablauf-und-termine

**Comment by jnccd** [comment]
> Meanwhile the explanation of the structure in https://docs.software-challenge.de/allgemein/wettkampf could be merged with https://software-challenge.de/ablauf-und-termine
Which one should we keep?

**Comment by xeruf** [comment]
The one on the website, see https://github.com/software-challenge/docs/issues/46
